version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: collab-board-db
    environment:
      POSTGRES_USER: collabboard
      POSTGRES_PASSWORD: collabboard_dev
      POSTGRES_DB: collabboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collabboard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
